### ISSUE TITLE
Add file upload UI to project page

### ISSUE THREAD

**Issue by neatonk** [cwdevteam/mesa#34]
### Requirements
- [ ] Multiple songs can be added to one project
- [ ] Store song with project.
- [ ] Limit access to project members.
- [ ] Include songs in project events (for timeline UI).

### TODO
- [ ] Prompt user for file to upload.
- [ ] Add file to storage.
- [ ] Add file metadata to database.
- [ ] Associate file with project and user account.
- [ ] Add to project timeline.
