### ISSUE TITLE
Add project timeline UI

### ISSUE THREAD

**Issue by neatonk** [cwdevteam/mesa#36]
### Requirements
- [ ] Display all project events in chronological order a la GitHub.

### TODO
- [ ] Design database schema for project events.
- [ ] Implement components to render each event type:
  - E.g. FileUpload, Comment, ProjectDetails, etc.
  - See https://docs.github.com/en/rest/overview/github-event-types for inspiration.
