### ISSUE TITLE
Track project events and attestations

### ISSUE THREAD

**Issue by neatonk** [cwdevteam/mesa#42]
### Requirements
- Require user to submit a signed attestation for each event.
- Verify and store signed attestation for each event.
- Do not process event if not verified.

### TODO
- [x] event: create project
- [ ] event: invite user
- [ ] event: accept invite
- [ ] event: update title
- [ ] event: modify description
- [ ] event: modify splits
