### ISSUE TITLE
Add dashboard page

### ISSUE THREAD

**Issue by neatonk** [cwdevteam/mesa#5]
### Requirements
- [x] Project listing for current user including: project name, description, and last update timestamp.
- [x] Includes all projects on which the user is a collaborator, including projects they created or were added to.
- [x] Sorted in reverse chronological order with the most recently updated projects first.
- [x] Click project name to view project page.
- [x] New project button, which creates a project and takes the user to it.
  - [x] Project splits default to 100% for project creator.
- [x] Prompt user to create a new project if there are none to list.

### TODO
- [x] Insert new row in `projects` table when "New Project" button is clicked.
- [x] List projects dashboard and link to each project page.
