### ISSUE TITLE
Add project page

### ISSUE THREAD

**Issue by neatonk** [cwdevteam/mesa#6]
### TODO
- [x] #40
- [x] #41
- [x] #42
- [x] Includes project details (name, description, collaborators/splits)~, files, notes, releases and timeline~.
- [x] #43
- [x] #44
  - [ ] send OTP code via supabase auth as invite email
  - [ ] new user needs to create MESA account and log into MESA to interact
